version: '3.9'

services:
  dash:
    command: python3 app.py
    image: akraradets/ait-ml-dash:2023
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8050:80
    volumes:
      - ./code:/app
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80